### ISSUE TITLE
Improving UI

### ISSUE THREAD

**Issue by umar-9540** [vigneshs-dev/Q-Vote#18]
![image](https://github.com/user-attachments/assets/8229b7b2-cbd0-45eb-b45f-7b8de7f4b7c1)

I can improve it like this if you please assign this to me. And i can add/improve anything else if you need, you can just tell me.

![image](https://github.com/user-attachments/assets/092c1a3c-37a8-4c8e-92ae-78f9de3a7428)

**Comment by vigneshs-dev** [comment]
Hi @umar-9540 , 
I have updated the core logic of this project to get votes from users after logging in. You can check that in the below given branch.
https://github.com/vigneshs-dev/Q-Vote/tree/login_voting_result_db

Once I complete that, You can show your idea for enhancement. Then we will proceed on this. Thankyou for asking. The core logic updation will complete within one day.

**Comment by vigneshs-dev** [comment]
Hi @umar-9540 , 
The backend enhancement was completed. Please go through the live website for once to get a view. After that give me your idea on enhancement. Then you can work on that part.

**Comment by vigneshs-dev** [comment]
I am closing this issue, as we have proceeded a long way from this part.
