### ISSUE TITLE
[Bug]: Docker File Not Working Correctly

### ISSUE THREAD

**Issue by vigneshs-dev** [vigneshs-dev/Q-Vote#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As the backend logic was updated, the earlier created Docker file wasn't running. Have to create new Docker file to run it correclty.

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by naylin-dev** [comment]
Could you assign me to this issue?

**Comment by vigneshs-dev** [comment]
Hi @naylin-dev ,
I tried to run your forked repo locally in my system. It's not running. Can you please check once again? 
I think there is some problem in port. In app.py you mentioned port as 5002 and in all other places your have mentioned 5000.

**Comment by naylin-dev** [comment]
Could you change it back to 5000 and run again? Port 5000 is already occupied on my machine. If you want I can change all port to 5002.

**Comment by vigneshs-dev** [comment]
> Could you change it back to 5000 and run again? Port 5000 is already occupied on my machine. If you want I can change all port to 5002.

I changed the port number from 5002 to 5000 in app.py and able to run that. Thankyou for your contribution. I will merge it with the main branch. Keep contributing.
