### ISSUE TITLE
[Bug]: Error messages are not showing on registration

### ISSUE THREAD

**Issue by rajmanna-dev** [vigneshs-dev/Q-Vote#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
Right now there was no error message handling when a user try to register with credentials that already exists in database.
Right now it just reload the register page.

### Expected behavior
When a user try to register with existing credentails, show a specific error message to the user.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by vigneshs-dev** [comment]
Yeah. Thankyou for spotting the bug. You can work on this issue to solve the problem. Along with that I also found another bug.
After Registering ,Logging and Casting vote, we get the Result page. At the result page when Logout button is pressed, I got the below response:

![image](https://github.com/user-attachments/assets/088d4147-59ef-4019-885f-2a8dd89c7129)

And also when registering with already registered user credentials, I got the following reponse:

![image](https://github.com/user-attachments/assets/924bdc6c-41bc-4dd2-bb41-8a07cea9a346)

These are other bugs I found. Can you solve all these bugs ? If you are able to find other bugs also, It will be great. If you are ok with solving all these bugs, I will assign it to you.

**Comment by rajmanna-dev** [comment]
Yes sure! Assign me, i will looked forward to the codebase.

**Comment by Skibo555** [comment]
Can I work on it?

**Comment by Skibo555** [comment]
Can I work on it?
