### ISSUE TITLE
[Feature Request]: Add Dark Mode

### ISSUE THREAD

**Issue by Hareesh0-inf** [vigneshs-dev/Q-Vote#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Today most people prefer dark mode to light mode. So, adding a dark mode will provide more comfort to the users

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by vigneshs-dev** [comment]
Sure @Hareesh0-inf . You can start working on this issue. Thankyou for contributing.
