### ISSUE TITLE
[Feature Request]: Update Voting and Results page with CSS styles.

### ISSUE THREAD

**Issue by vigneshs-dev** [vigneshs-dev/Q-Vote#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

You have to update the Voting and Results page as same as of Login and Sign up page CSS styles.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by vigneshs-dev** [comment]
Hi @Priyanshu-su30,
You can work on this issue. I am very eager to see your work on this.

**Comment by Priyanshu-su30** [comment]
Sure I'll work on this assign me
