### ISSUE TITLE
[Feature Request]: DarkMode Toggle

### ISSUE THREAD

**Issue by vigneshs-dev** [vigneshs-dev/Q-Vote#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

You can add feature to toggle between Dark or Light mode.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Sarveshk76** [comment]
I would like to work on this issue

**Comment by vigneshs-dev** [comment]
> I would like to work on this issue

Nice. You can work on this issue. Thankyou for contributing.
