### ISSUE TITLE
[Feature Request]: SignUp / LogIn page 

### ISSUE THREAD

**Issue by vigneshs-dev** [vigneshs-dev/Q-Vote#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

You can add SignUp/LogIn page to get details of Votes.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by Priyanshu-su30** [comment]
Assign me the issue I'll work on it

**Comment by vigneshs-dev** [comment]
> Assign me the issue I'll work on it

Nice. You can work on this issue. Thankyou for contributing.

**Comment by Karan1962** [comment]
hey @Priyanshu-su30 are you working on it ?

**Comment by Priyanshu-su30** [comment]
Yes give me some time just got some college stuff

**Comment by vigneshs-dev** [comment]
> hey @Priyanshu-su30 are you working on it ?

Sorry @Karan1962 , This issue was already assigned to @Priyanshu-su30 . Can you please work on some other issues if you are interested.

**Comment by Karan1962** [comment]
Okay @vigneshs-dev and @Priyanshu-su30 . Just clarifying things as I am new to opensource. Apologies for any inconvenience. Will find another issue to work on.

**Comment by Priyanshu-su30** [comment]
No worries buddy.

**Comment by vigneshs-dev** [comment]
> No worries buddy.

Hi @Priyanshu-su30 , 
I updated the project with new logic and architecture. Please go through that once. You can also use live website for latest code which is currently running. Thankyou.

**Comment by Priyanshu-su30** [comment]
Sure @vigneshs-dev I will check it out

**Comment by vigneshs-dev** [comment]
> Sure @vigneshs-dev I will check it out

Hi @Priyanshu-su30 , 
I have created a basic SignUp, Login, Vote and Result page. I think you have to take a look. This is the logic from now on.

https://github.com/vigneshs-dev/Q-Vote/tree/login_voting_result_db

**Comment by Priyanshu-su30** [comment]
@vigneshs-dev Yup I'm on it

**Comment by Priyanshu-su30** [comment]
@vigneshs-dev kindly add hacktoberfest-accepted label
