### ISSUE TITLE
[DevOps Update]: Dockerize the Q-Vote

### ISSUE THREAD

**Issue by vigneshs-dev** [vigneshs-dev/Q-Vote#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to Dockerize the Q-Vote so that it can run on any system ( Linux/Windows/MacOS ) without any dependencies.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue
- [ ] I'm willing to provide further clarification or assistance if needed.

**Comment by PanGan21** [comment]
Hi, I created a pr in #11  that most likely resolves this issue.
Please let me know what you think!

**Comment by vigneshs-dev** [comment]
> Hi, I created a pr in #11 that most likely resolves this issue. Please let me know what you think!

Please ask before you work on any issue @PanGan21 . Otherwise the Repo owner don't know who are all working. I will check once your repo. Thanks for contributing.

**Comment by vigneshs-dev** [comment]
Hi @PanGan21 ,
I cloned your repo and try to run the Docker file by following the steps given in README.md file. But, the webpage is not loading in that port on my system. Please resolve the issues. 

Along with that, I updated the repo with new changes. Mainly, changed the location of requirements.txt file into the src directory to run the server in onrender website. Please update the file path changes to the Docker file also.
Use commands:

```
git remote add upstream https://github.com/vigneshs-dev/Q-Vote.git
git fetch upstream
git merge upstream/main
```

**Comment by PanGan21** [comment]
Hi @vigneshs-dev  the issue should be fixed now

**Comment by vigneshs-dev** [comment]
Thanks for contributing @PanGan21 . The Dockerfile works completly fine. I merged your PR with main branch. Your work means a lot to me. Keep contributing.

**Comment by PanGan21** [comment]
> Thanks for contributing @PanGan21 . The Dockerfile works completly fine. I merged your PR with main branch. Your work means a lot to me. Keep contributing.

Thank you and happy to contribute! Keep the project running because it looks a nice idea!

**Comment by vigneshs-dev** [comment]
> > Thanks for contributing @PanGan21 . The Dockerfile works completly fine. I merged your PR with main branch. Your work means a lot to me. Keep contributing.
> 
> Thank you and happy to contribute! Keep the project running because it looks a nice idea!

Definitely. Thanks once again.
